### ISSUE TITLE
Gold nugget recipe is missing

### ISSUE THREAD

**Issue by JajajaCZ** [FTBTeam/FTB-Presents-Direwolf20-1.16#252] opened 2021-04-12 20:41 UTC
* **Modpack Version**:  1.8.0

* **Issue**: It is not possible to craft gold nuggets from gold ingot

* **Link to Log or Crash File Paste**: I dont have any logs

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Minecraft

* **Known Fix**:

**Comment by Sunekaer** [comment] 2021-04-12 22:10
Okay, so technically this is not a bug Reliquary overrides the vanilla recipe.
We will add a recipe for ingot to nugget

**Comment by SonicSpeedster16** [comment] 2021-04-13 11:31
Looks like the Reliquary author will be releasing a fix for this later today: https://github.com/P3pp3rF1y/Reliquary/issues/510

**Comment by P3pp3rF1y** [comment] 2021-04-13 12:13
It's now fixed in latest Reliquary release https://www.curseforge.com/minecraft/mc-mods/reliquary-v1-3/files/3274714 so you should just need to update the mod and no need for extra recipe.

**Comment by Sunekaer** [comment] 2021-04-13 16:04
Thanks @P3pp3rF1y

**Comment by Sunekaer** [comment] 2021-04-18 09:44
New version released

**Closed by Sunekaer** 2021-04-18 09:44 UTC
Labels: Mod bug
