### ISSUE TITLE
Void Ore Miner Server Crash

### ISSUE THREAD

**Issue by Lurae** [FTBTeam/FTB-Presents-Direwolf20-1.16#93] opened 2021-01-08 11:33 UTC
Modpack Version: 1.2.0

Issue: I have entered the mining world and placed my void ore miner (orientation doesnt seem to matter), upon completion and having power connected, the server crashes. Upon the server crashing, the below attached log is generated when trying to start up again and just keep crashing straight after the server has started so the world is somehow corrupt.

Link to Log or Crash File Paste: https://paste.feed-the-beast.com/view/26a3fca5

Is it Repeatable?: Re-tested this placing the void ore miner in various orientations via a server backup and it is repeatable

Mod/s Affected: Environmental Tech or maybe its just the mining world???

Known Fix: unknown at this time, will continue testing

**Comment by luchokoldo** [comment] 2021-01-08 12:05
Valk updated ET3 a week ago; maybe is fixed in the last update

ValkyrieLib Version: 3.0.6.1: 
https://www.curseforge.com/minecraft/mc-mods/valkyrielib/files
Bug fixes for FluidIOHandlers
Bug fixes for Item transfer
Added EnergyIOHandler
Added Multiblock Auto-Utility gui for constructing and breaking the multiblock.(Will be adding list of all constructable orientations to select from in future, current gui is temporary one and still uses players physical look direction to properly construct the multiblock. Youll need to look in a different direction if it says invalid construction direction)
Fixed SidedIO configs
Fixed multiblock components not dropping.

Environmental Core Version 3.0.6.0: 
https://www.curseforge.com/minecraft/mc-mods/environmental-core/files
Fixed CCU coloring with RGB Controller
Added ability to access multiblock gui from any Structure Panel/Frame when the multiblock is correctly constructed
Fixed assembler SidedConfig
Fixed some IO blocks not saving their upgrades
Fixed some weirdness with the assembler crafting Modifiers

**Comment by Sunekaer** [comment] 2021-01-08 13:14
duplicate of #51

**Closed by Sunekaer** 2021-01-08 13:14 UTC
Labels: duplicate
