### ISSUE TITLE
Rendering issues only in SMP

### ISSUE THREAD

**Issue by RyabDev** [FTBTeam/FTB-Presents-Direwolf20-1.16#143] opened 2021-01-21 00:10 UTC
![Rendering](https://user-images.githubusercontent.com/16693525/105256066-fc1ae900-5b52-11eb-9d4d-8b54e3629c4c.png)
Many blocks from Mana and Artifice and Immersive Engineering are rendering completely wrong on servers

**Comment by RyabDev** [comment] 2021-01-21 00:10
The waterlogged slab is bauxite ore for example

**Comment by Sunekaer** [comment] 2021-01-21 15:35
issue template not followed, please post an update with following the issue template there was given when creating the issue, else the issue will be closed

**Comment by simfrek** [comment] 2021-01-22 01:42
This is on newest version of pack, 1.4.1 
I have also found this exact same issue, it is effecting all blocks from the following mods:
Storage draws, Structurize, Flux Networks, Mana and Artifice, moving elevators, Psi, Rats, statues mod
It seems to be any blocks from these mods that use a custom rendering, rather that a flat texture.
This issue only seems to effect servers, not single player

**Comment by Sunekaer** [comment] 2021-01-22 08:24
so duplicate of 1#39

**Closed by Sunekaer** 2021-01-22 08:24 UTC
Labels: duplicate
