### ISSUE TITLE
Huge Difference in endermen spawn rates between Direwolf1.16 - 1.1.2 and 1.2.0

### ISSUE THREAD

**Issue by DalasaurusRex** [FTBTeam/FTB-Presents-Direwolf20-1.16#61] opened 2020-12-30 21:35 UTC
* **Modpack Version**: Direwolf 1.16-1.2.0

* **Issue**: Upon updating to the latest version of the modpack (1.2.0). I discovered that my enderman farm's efficiency drastically decreased. I didnt think of the pack version being a variable, so i ran quite a few tests and happened to accidentally downgrade a different instance of the pack. I found that enderman spawn were greatly reduced between pack versions.

 Here is a video of the difference in spawns. https://youtu.be/tQM8J4qh8KM

**Comment by SonicSpeedster16** [comment] 2020-12-30 21:49
Duplicate of Issue #53

**Closed** 2020-12-31 00:32 UTC
Labels: duplicate
