### ISSUE TITLE
Game stuck/crashes while exploring

### ISSUE THREAD

**Issue by djanse** [FTBTeam/FTB-Presents-Direwolf20-1.16#90] opened 2021-01-07 17:04 UTC
* **Modpack Version**: 1.2.0

* **Issue**: 
When exploring the overworld, specificly 2385 76 -83 the server starts hanging. after about a minute we get kicked out and the server is shut down.

* **Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/2dac8e80

* **Is it Repeatable?**: 
Yes, everytime we boot up the server and go to these coordinates the server _gets stuck/crashes_
But going to the same place in a singleplayer environment does not cause issues. (seed: -2936243634065170807)

**Comment by djanse** [comment] 2021-01-07 17:22
Edit: i had a friend try singleplayer aswell and the game got really slow for him there aswell.

**Comment by n4imLess** [comment] 2021-01-07 23:58
Probably a duplicate of #84 (or at least related in some way)

**Closed** 2021-01-08 09:22 UTC
Labels: duplicate
