### ISSUE TITLE
Unable to create Mining Turtles (CC: Tweaked)

### ISSUE THREAD

**Issue by natiiix** [FTBTeam/FTB-Presents-Direwolf20-1.16#25] opened 2020-12-22 09:33 UTC
* **Modpack Version**: 1.1.1 (also present in at least 1.1.0)

* **Issue**: It is impossible to craft mining (and other specialized) turtles from CC: Tweaked. It is also impossible to equip a diamond pickaxe onto a turtle. I tested this with both the turtle and the diamond pickaxe freshly crafted, which should work according to every available tutorial. The recipe shows up in JEI and JEI happily puts the items into the crafting table grid, but no crafting result shows up. Also tested in creative; also didn't work.

* **Link to Log or Crash File Paste**: There's nothing relevant in the logs.

* **Is it Repeatable?**: Yes, you can see many people complaining about this issue over the past few days on CurseForge (e.g., https://www.curseforge.com/minecraft/mc-mods/cc-tweaked?comment=233)

* **Mod/s Affected**: CC: Tweaked

* **Known Fix**: N/A

**Comment by MacChuck** [comment] 2020-12-22 20:21
Very weird. I just tested this in 1.1.1 in a fresh flat creative map for testing. Something seems to be causing extra NBT tags to show up on the pick but I'm not sure of the specific conditions.

First time, spawned in a diamond pick and turtle using JEI. Couldn't craft the turtle with the pickaxe
Put the pickaxe into the turtle's inventory and tried to equip using turtle.equipLeft() and it failed with "invalid upgrade". Looking at the diamond pick it had two NBT tags (I didn't check what they were, sorry).

Deleted the items, spawned in a new diamond pick and turtle using JEI, and crafting and equipping worked, with the pickaxe having 1 NBT tag.

**Comment by Lupus590** [comment] 2020-12-22 20:27
Just attempted to reproduce on DW20 1.16 v1.1.2 and I could not reproduce it. I managed to craft a mining turtle with a vanilla crafting table,

**Comment by MacChuck** [comment] 2020-12-22 20:32
I'm not sure how to read/list all of the NBT data on an item, so I can't check what the 2nd tag being added when the pick is selected on the hotbar is.

**Comment by billybricker** [comment] 2020-12-22 20:57
I installed CraftTweaker and ran /ct hand on the pick.

<item:minecraft:diamond_pickaxe>.withTag({Damage: 0 as int, AS_Amulet_Holder: [-484640039, 376718482, -1110532970, -1922222290]})

It seems to be an Astral Sorcery tag that gets added when the pick goes into any hotbar slot. The recipe works if the pick doesn't have that tag.

**Comment by SquidDev** [comment] 2020-12-22 21:47
Ok, that'll be the problem. CC requires the item not to have any (non-capability) NBT data. I guess this was originally done to prevent accidentally using enchanted items, as enchantments are reset when unequipping.

I guess I can relax the restrictions on CC's end. I don't know if AS can also defer adding NBT, or if needs to be this early - haven't looked into their code at all.

**Comment by MacChuck** [comment] 2020-12-23 01:28
Could it be fixed in the pack with a custom recipe via kubejs? (don't know enough about it to know if that's possible)

**Comment by Sunekaer** [comment] 2020-12-27 23:31
That would be great if you could @SquidDev

**Comment by SquidDev** [comment] 2021-01-07 16:50
Should be fixed in CC:T 1.95.0, which was included in 1.2.0 of the pack.

**Closed** 2021-01-09 11:08 UTC
